//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDNhapHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDNhapHang()
        {
            this.ChiTietHDNhaps = new HashSet<ChiTietHDNhap>();
        }
    
        public string MaHD { get; set; }
        public string MaNCC { get; set; }
        public string NgayGiao { get; set; }
        public string NgayNhan { get; set; }
        public int ThanhTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDNhap> ChiTietHDNhaps { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
