//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        public string MaNV { get; set; }
        public string MaCa { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual CaLam CaLam { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
